AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create SFTP

Parameters:
#  HostedZoneIdParam:
#    Type: String
#    Description: Hosted Zone ID
  SFTPHostnameParam:
    Type: String
    Description: Hostname for the SFTP Server

Resources:
  SFTPServer:
    Type: AWS::Transfer::Server
    Properties:
      EndpointType: PUBLIC
      Tags:
        - Key: Application
          Value: sftpserver-beta

#  SFTPServerDNSRecord:
#    Type: AWS::Route53::RecordSet
#    Properties:
#      Name: !Ref SFTPHostnameParam
#      HostedZoneId: !Ref HostedZoneIdParam
#      Type: CNAME
#      Comment: SFTP Transfer custom hostname
#      TTL: 300
#      ResourceRecords:
#        - !Sub ${SFTPServer.ServerId}.server.transfer.${AWS::Region}.amazonaws.com

  SFTPServerS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: testbucket1-sftp
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Application
          Value: sftpserver-beta

  SFTPUserRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - transfer.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3FullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Resource: "*"
        - PolicyName: AllowListingOfUserFolder
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt SFTPServerS3Bucket.Arn
        - PolicyName: HomeDirObjectAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                Resource: !Sub "${SFTPServerS3Bucket.Arn}/*"

  TestUser:
    Type: AWS::Transfer::User
    Properties:
      ServerId: !GetAtt SFTPServer.ServerId
      UserName: sftpuser
      HomeDirectory: !Sub "/${SFTPServerS3Bucket}/home/sftpuser"
      Policy: >
          {
            "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Sid": "AllowListingOfUserFolder",
                            "Effect": "Allow",
                            "Action": "s3:ListBucket",
                            "Resource": "arn:aws:s3:::${transfer:HomeBucket}",
                            "Condition": {
                                "StringLike": {
                                    "s3:prefix": [
                                        "home/${transfer:UserName}/*",
                                        "home/${transfer:UserName}"
                                    ]
                                }
                            }
                        },
                        {
                            "Sid": "HomeDirObjectAccess",
                            "Effect": "Allow",
                            "Action": [
                                "s3:PutObject",
                                "s3:GetObject",
                                "s3:GetObjectVersion",
                                "s3:DeleteObject",
                                "s3:DeleteObjectVersion"
                            ],
                            "Resource": "arn:aws:s3:::${transfer:HomeDirectory}*"
                        }
                    ]
            }
      Role: !GetAtt SFTPUserRole.Arn
      SshPublicKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAj/xsDZLcR2E85NN416MgQt09nE/Jn33EQHRkCq2ERt2iK1uAV7THFBnOiuY5DMfnLFWl66IpbJhga9AOqarVQ/qr7gG480iwPb5g4LnBWf2yGW5QbWaE58JZucxygXc64H35+FDN88ve4MA9dJjqtzCqQmbfVCIuJCGC7D6NbO3dEqQf0dUG+qAD0KBG9XQkiUzbCNtY0QChbVsddDBEh6iRMrjUdqdmkFIaI3mT+RF/abdZW30A7tmIFqXvTT36ZnzrtSebG7kgJrgMk/doaPH7DVnXBMtoEtvs2KwvAzqK1lW32rQp6MBCVW/jE1aBe6JfBJyg1nMOm2QvMS353dPdEQhkRzVn2FHseXw1BUNj+FPMP8krBTXrPG+GKligesg+GF6dky/+H50OUeMlN5lVzfbh4DYpeUdtNGc17O5qM3pAfZqs1w0TnewFIeXILVES2irEQcudxAstqp6rtc7u3MpzfMakj0TWoCvBgs7dFSAnzvbVxDB4j6WGdAc= madanraj@Holygrail
      Tags:
        - Key: Application
          Value: sftpserver-beta